title: "Danyi Li, MPH, MSP, MPP, LLB"
description: "Personal Academic Website"
url: "https://danyili525.github.io"
baseurl: ""
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - publications.md
  - projects.md
  - teaching.md
  - cv.md
  - life-out-of-academia.md
