title: "Danyi Li, MPH, MSP, MPP, LLB"
description: "Personal Academic Website"
url: "https://danyili525.github.io"
baseurl: ""
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - home.html
  - publications.html
  - projects.html
  - teaching.html
  - cv.html
  - life-out-of-academia.html
